# ===== DATABASE PROD ====
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.hikari.data-sorurce-properties.sslmode=require

# ===== JWT ====
jwt.secret={JWT_SECRET}

# ===== JPA ====
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# ===== LOGGING ====
logging.level.root=INFO
logging.level.org.springframework=WARN

# ===== CLOUDINARY INFO ====
cloudinary.name=${CLOUDINARY_NAME}
cloudinary.key=${CLOUDINARY_KEY}
cloudinary.secret=${CLOUDINARY_SECRET}


