# ===== DATABASE DEV ====
spring.datasource.url=${POSTGRESQL_URL}
spring.datasource.username=${POSTGRESQL_USERNAME}
spring.datasource.password=${POSTGRESQL_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

allowed.origins=http://localhost:5173
# ===== JWT ====
jwt.secret=${JWT_SECRET}

# ===== LOGGING ====
logging.level.org.springframework=INFO
logging.level.com.onlyphones=DEBUG

# ===== CLOUDINARY INFO ====
cloudinary.name=${CLOUDINARY_NAME}
cloudinary.key=${CLOUDINARY_KEY}
cloudinary.secret=${CLOUDINARY_SECRET}